version: "3.6"
services:
  redalert:
    image: ynixon/walert
    container_name: walert
    restart: always
    environment:
      LOG_LEVEL: "INFO"                   # Options: DEBUG, INFO, WARNING, ERROR, OFF
      REGION: "*"                         # Use "*" for all regions or specify a region name
      INCLUDE_TEST_ALERTS: "False"        # Set to "True" to include test alerts
      GREEN_API_INSTANCE: "your_green_api_instance"  # Replace with actual instance ID
      WHATSAPP_NUMBER: "your_whatsapp_number"        # Format as number@c.us for contacts or number@g.us for groups
      GREEN_API_TOKEN: "Your Green API token"        #  for authentication.
