version: "3.6"
services:
  redalert:
    build: .
    container_name: walert
    dns:
      - 8.8.8.8  # Google's DNS server
    restart: always
    environment:
      LOG_LEVEL: "INFO"
      REGION: "רמת השרון"
      INCLUDE_TEST_ALERTS: "False"
      GREEN_API_INSTANCE: "7103143441"
      WHATSAPP_NUMBER: "972507635853-1345486715@g.us"
      GREEN_API_TOKEN: "bba103483d55467ebed97b63a0bb444c38d6b9acffd84dc28f"
      DEDUP_WINDOW_SECONDS: "120"
