name: "Create Release"

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Docker Build"]
    types:
      - completed  

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get semantic version from file
        run: |
          SEMVER=$(cat VERSION | tr -d ' \t\n\r')
          echo "SEMVER=$SEMVER" >> $GITHUB_ENV

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Set Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create Git Tag
        run: |
          git tag -a "${{ env.SEMVER }}" -m "Release version ${{ env.SEMVER }}"
          git push origin "${{ env.SEMVER }}"
        env:
          SEMVER: ${{ env.SEMVER }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Release
        run: gh release create "${{ env.SEMVER }}" -t "Release ${{ env.SEMVER }}" -n "Automatic release based on version ${{ env.SEMVER }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          SEMVER: ${{ env.SEMVER }}
