name: "Docker Build"

on:
  push:
    branches:
      - main        # or specify other branches as needed
  workflow_dispatch:  # Allows manual dispatch
  workflow_run:
    workflows: [Create Release]
    types:
      - completed  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get semantic version from file
        run: echo "SEMVER=$(cat VERSION | tr -d ' \t\n\r')" >> $GITHUB_ENV
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ynixon/walert:latest
            ynixon/walert:${{ env.SEMVER }}
